apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 80          # Port exposed outside Kubernetes
      targetPort: 3000  # Port inside the container
  type: NodePort        # Exposes the service on a specific NodePort

